# Generated by Django 5.2 on 2025-04-14 21:23

import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(upload_to=videos.models.video_upload_to),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "option_selected",
                    models.CharField(default="option1_grabar", max_length=100),
                ),
                (
                    "threshold_selected",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("lang", models.CharField(blank=True, max_length=50, null=True)),
                ("tone", models.CharField(blank=True, max_length=50, null=True)),
                ("voice_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to=videos.models.video_upload_to
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("start_at", models.DurationField()),
                ("end_at", models.DurationField()),
                ("duration", models.DurationField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="", max_length=100)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="videos.video",
                    ),
                ),
            ],
        ),
    ]
