# Generated by Django 5.2 on 2025-06-17 18:04

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="modified_audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to=videos.models.video_upload_to
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="modified_video_file",
            field=models.FileField(
                blank=True, null=True, upload_to=videos.models.video_upload_to
            ),
        ),
    ]
