# Generated by Django 5.2 on 2025-06-17 18:22

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_modified_video_modified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="web_vtt_file",
            field=models.FileField(
                blank=True, null=True, upload_to=videos.models.video_upload_to
            ),
        ),
    ]
