# Generated by Django 5.2 on 2025-06-23 20:10

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_recordingdescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=videos.models.description_audio_upload_to,
            ),
        ),
    ]
