# Generated by Django 5.2 on 2025-06-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_description_audio_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecordingDescription",
        ),
    ]
