# Generated by Django 5.2 on 2025-06-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_delete_recordingdescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="lang",
        ),
        migrations.RemoveField(
            model_name="video",
            name="tone",
        ),
    ]
