# Generated by Django 5.2 on 2025-04-05 18:22

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=pathlib.PurePosixPath('/Users/francip/Desktop/TFM-Back/media')),
        ),
    ]
