# Generated by Django 5.2 on 2025-04-05 18:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='option_selected',
            field=models.CharField(default='option1_grabar', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=api.models.video_upload_to),
        ),
    ]
