# Generated by Django 5.2 on 2025-04-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_video_option_selected_alter_video_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="lang",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="lang_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="threshold_selected",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="threshold_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="tone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="voice_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
