# Generated by Django 5.2 on 2025-04-13 19:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_video_lang_video_lang_name_video_threshold_selected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to=api.models.video_upload_to
            ),
        ),
    ]
