# Generated by Django 5.2 on 2025-04-13 21:11

from django.db import migrations, models
from datetime import timedelta

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_video_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="duration",
            field=models.DurationField(default=timedelta(seconds=0.5)),
            preserve_default=False,
        ),
    ]
