# Generated by Django 5.2 on 2025-04-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_description_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="lang_name",
        ),
    ]
