# Generated by Django 5.2 on 2025-04-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_video_lang_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Description",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
